function(nice_target_sources target src_loc)
    set(_visibility "")
    set(_batch "")
    set(_all_files "")
    foreach(entry ${ARGN})
        if (entry STREQUAL "PRIVATE" OR entry STREQUAL "PUBLIC" OR entry STREQUAL "INTERFACE")
            if (_batch)
                target_sources(${target} ${_visibility} ${_batch})
                set(_batch "")
            endif()
            set(_visibility "${entry}")
        else()
            set(_full "${src_loc}/${entry}")
            list(APPEND _batch "${_full}")
            list(APPEND _all_files "${_full}")
        endif()
    endforeach()
    if (_batch)
        target_sources(${target} ${_visibility} ${_batch})
    endif()
    if (_all_files)
        source_group(TREE "${src_loc}" PREFIX "Sources" FILES ${_all_files})
    endif()
endfunction()
