if(WIN32)
    set(_BUILD_UM_DEFAULT ON)
    set(_BUILD_KM_DEFAULT ON)
    set(_BUILD_TESTS_DEFAULT ON)
else()
    set(_BUILD_UM_DEFAULT OFF)
    set(_BUILD_KM_DEFAULT OFF)
    set(_BUILD_TESTS_DEFAULT OFF)
endif()
option(BUILD_UM "Build user-mode client" ${_BUILD_UM_DEFAULT})
option(BUILD_KM "Build kernel-mode driver" ${_BUILD_KM_DEFAULT})
option(BUILD_TESTS "Build host-side unit tests (googletest)" ${_BUILD_TESTS_DEFAULT})
unset(_BUILD_UM_DEFAULT)
unset(_BUILD_KM_DEFAULT)
unset(_BUILD_TESTS_DEFAULT)
